//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingAgency.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishingAgencyEntities2 : DbContext
    {
        public FishingAgencyEntities2()
            : base("name=FishingAgencyEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catch> Catches { get; set; }
        public virtual DbSet<FishingShip> FishingShips { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
